[package]
name = "shitty-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
criterion = "0.5.1"

[[bench]]
name = "poseidon"
harness = false
